version: '3'

services:
  master:
    image: mpkeet/loku:3
    ports:
     - "8089:8089"
    volumes:
      - ./:/locust-tasks
    command: -f /locust-tasks/locustfile.py --master -H http://master:8089
  
  worker:
    image: mpkeet/loku:3
    volumes:
      - ./:/locust-tasks
    command: -f /locust-tasks/locustfile.py --worker --master-host master
