# Default values for loku-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

master:
  replicaCount: 1
  image: 
    repository: 
    tag: latest
    pullPolicy: IfNotPresent

worker:
  replicaCount: 3
  image: 
    repository: 
    tag: latest
    pullPolicy: IfNotPresent

targetHost: 